### ISSUE TITLE
What can this Emailing do?

### ISSUE THREAD

**Issue by BoydYang** [Trejjam/Emailing#1]
What can this Emailing do?

**Comment by Trejjam** [comment]
It enable decompose sending huge amount of email using Rabbit queue.

Example:
You want send n*100 emails (and not use CC). You send request to your RabbitMQ server (this is very fast), Rabbit temporary store your messages.

Then your RabbitMQ worker (working in background) send all emails in couple of minutes.

Pros:
fast responsing app

Cons:
Own RabbitMQ server

Other behavior:
- using Nette Framework, Nette Database, Kdyby/RabbitMQ

**Comment by BoydYang** [comment]
Thanks!

It says "save email to IMAP",  Do you use SMTP or IMAP to send emails?
Is this right?
Client(Outlook for exampl)--(IMAP)-->RabbitMQ--(IMAP)-->MailServer
Or
Client(Outlook for exampl)--(SMTP)-->RabbitMQ--(SMTP)-->MailServer
?

**Comment by Trejjam** [comment]
It is little bit difficult. This is extension for PHP (programming language) Nette Framework. You could not use it with Outlook, Thunderbird or what ever fat client.

Yes, I said use IMAP. After this extension send email it could save it to configured IMAP server.
So basically it looks like:
Web browser - web server with PHP and [Nette Framework](https://nette.org) - this extension - RabbitMQ queue 1.
Queue 1 - SMTP server (and queue 2 - optionally).
Queue 2 - IMAP server.
